### ISSUE TITLE
NTR: Request for S18 heat

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S18#10]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>heat <p><b>Definition</b><p> Energy transferred to or from a thermodynamic system, by means of convection, conduction, radiation or friction.<p><H2> Optional </H2><p><b>Sources/references</b><p>nvs-vocabs/P01/issues/157<p>

**Comment by danibodc** [comment]
This term has been loaded and will be live on the NVS from tomorrow morning.

**Comment by danibodc** [comment]
This term is now live on the NVS:
http://vocab.nerc.ac.uk/collection/S18/current/S1800101/
