### ISSUE TITLE
NTR: Request for S18 instrument's profile

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S18#13]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>instrument's profile <p><b>Definition</b><p> The property relates to the vertical trajectory of a measuring instrument.<p><H2> Optional </H2><p>

**Comment by SLBlakeman** [comment]
S18 term created and included in an S29 term. 

S18:
[instrument's profile](http://vocab.nerc.ac.uk/collection/S18/current/S1800106/) 

S29:
[instrument's profile](http://vocab.nerc.ac.uk/collection/S29/current/PE001496/)
