### ISSUE TITLE
NTR: Request for S18 sampling track

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S18#15]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>sampling track <p><b>Definition</b><p> The route along which a sample was collected or an observation was made, such as a beach transect, the track of a sampling net through water, or the track of a benthic sampler along the seafloor. It can also include the passage or transit between sampling or observation locations.<p><H2> Optional </H2><p>

**Comment by danibodc** [comment]
This term has now been loaded and will be live on the NVS from 0730 UTC tomorrow mornng.

S1800107	sampling track

**Comment by danibodc** [comment]
http://vocab.nerc.ac.uk/collection/S18/current/S1800107/
