### ISSUE TITLE
NTR: Request for S18 representative sample

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S18#16]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>representative sample <p><b>Definition</b><p> Term to be used to qualify or quantify a representative sample like e.g. a size threshold below which a sample is no longer representative.<p><H2> Optional </H2><p><b>Sources/references</b><p> http://vocab.nerc.ac.uk/collection/P01/current/NEWCXX01/<p>

**Comment by gwemon** [comment]
Live on the NVS: http://vocab.nerc.ac.uk/collection/S18/current/S1800110/
