### ISSUE TITLE
NTR: Request for S18 geomorphological feature

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S18#17]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>geomorphological feature <p><b>Definition</b><p> A topographic or bathymetric feature of the seafloor, coastline or terrestrial land surface created by physical, chemical or biological processes, such as beaches, dunes, bedforms, seamounts and ridges. <p><H2> Optional </H2><p>

**Comment by danibodc** [comment]
Associated with https://github.com/nvs-vocabs/P01/issues/215

**Comment by danibodc** [comment]
This term has now been loaded and will be live on the NVS from 0730 UTC tomorrow morning: 

S1800112	geomorphological feature

**Comment by danibodc** [comment]
https://vocab.nerc.ac.uk/collection/S18/current/S1800112/
