### ISSUE TITLE
NTR: Request for S18 river water

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S18#18]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>river water <p><b>Definition</b><p> The liquid phase plus any dissolved material and suspended solids making up the body of rivers or streams.<p><H2> Optional </H2><p>

**Comment by danibodc** [comment]
Associated with https://github.com/nvs-vocabs/P01/issues/202

**Comment by danibodc** [comment]
S1800113	river water

Definition:
The liquid phase plus any dissolved material and suspended solids making up the body of rivers or streams. Rivers and streams are defined as being upstream of the tidal limit.

**Comment by danibodc** [comment]
https://vocab.nerc.ac.uk/collection/S18/current/S1800113/
