### ISSUE TITLE
NTR: liquid water equivalent

### ISSUE THREAD

**Issue by vpaba** [nvs-vocabs/S18#19]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>liquid water equivalent <p><b>Definition</b><p>Measurement of water in liquid state<p><H2> Optional </H2><p>

.<p><H2> Background info</H2><p>To model P01 codes CPRRRG01: Precipitation rate (liquid water equivalent) in the atmosphere by in-situ rain gauge, and CPRPRG01: Thickness of precipitation amount (liquid water equivalent) in the atmosphere by in-situ rain gauge

**Comment by vpaba** [comment]
Note: definition to review @gwemon

**Comment by gwemon** [comment]
Definition taken from: https://forecast.weather.gov/glossary.php?word=water%20equivalent#:~:text=Liquid%20Water%20Equivalent,the%20refreezing%20of%20melted%20snow (05-Jun-2024):
Liquid Water Equivalent
Same as Water Equivalent; the liquid content of solid precipitation that has accumulated on the ground (snow depth). The accumulation may consist of snow, ice formed by freezing precipitation, freezing liquid precipitation, or ice formed by the refreezing of melted snow.
Snow Water Equivalent
The water content obtained from melting accumulated snow.
Water Equivalent
The liquid content of solid precipitation that has accumulated on the ground (snow depth). The accumulation may consist of snow, ice formed by freezing precipitation, freezing liquid precipitation, or ice formed by the refreezing of melted snow.

**Comment by gwemon** [comment]
New term created and new S29 compiled. Queued for publication on the NVS.

**Comment by danibodc** [comment]
http://vocab.nerc.ac.uk/collection/S29/current/PE001545/
