### ISSUE TITLE
NTR: sample

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/S18#2]
New physical entity definition needed for "sample" to be used for the re-modelling of existing P01 codes describing attributes of a physical sample e.g. Wet weight of sample, Dry weight of sample, Volume of sample, area sampled etc..

It could be defined fairlyt broadly as: 
"A portion of material substance or digital record to be used for an analysis. It includes portions that are physically removed from an environment or portions that are subsets of a remote observation or subsets of a digital recording."
Or made more specific to physical samples e.g.
"A portion of material substance to be used for an analysis that is physically removed from an environment."

The new term will then be used to remodel the following P01 codes, e.g.
[PEWCXX02](https://vocab.nerc.ac.uk/collection/P01/current/PEWCXX02/)	Dry weight of sample
by making it a combination of [S06 for dry weight](http://vocab.nerc.ac.uk/collection/S06/current/S0600148/) and the new S18/S29 term
[NEWCXX02](https://vocab.nerc.ac.uk/collection/P01/current/NEWCXX02/)      Wet weight of sample >> Same as above but for wet weight
[VOLWBSMP](https://vocab.nerc.ac.uk/collection/P01/current/VOLWBSMP/)	Volume sampled of the water body >> new preflabel would become: Volume of sample of the water body 
[VOLSEDSM](https://vocab.nerc.ac.uk/collection/P01/current/VOLSEDSM/)     Volume sampled of sediment >> new preflabel would become: Volume of sample of sediment
[AREABEDS](https://vocab.nerc.ac.uk/collection/P01/current/AREABEDS/)	Area sampled of the bed >> Area of sample of the bed
[WASPXX01](https://vocab.nerc.ac.uk/collection/P01/current/WASPXX01/)	Area sampled of the bed by image analysis >> Area of sample of the bed by image analysis
[SAMPARAC](https://vocab.nerc.ac.uk/collection/P01/current/SAMPARAC/) | Sample area (aircraft survey) >> Area of sample by aircraft survey
[VOLFFMXX](https://vocab.nerc.ac.uk/collection/P01/current/VOLFFMXX/) | Sample volume (filtration) by flow meter >> Volume of sample filtered by flow meter
[VOLSPOPC](https://vocab.nerc.ac.uk/collection/P01/current/VOLSPOPC/) | Sample volume (optical plankton recorder count) >> Volume of sample by optical plankton recorder

**Comment by gwemon** [comment]
@dr-shorthair I am proposing to create this new "sample" term in collection S18 and map it to http://www.w3.org/ns/sosa/Sample with owl:sameAs 
The alternative would be to make the S18 term specific to physical samples and map to http://www.w3.org/ns/sosa/Sample with skos broad/narrow relationship






 

This term would be related to another S18 term for "sampling" (http://www.w3.org/ns/sosa/Sampling) to capture information about the sampling event
e.g.

**Comment by roswri** [comment]
New term created:
S18: S1800108 - sample

**Comment by gwemon** [comment]
The following concepts have now been remodeled to the BODC PUV:
[VOLXXXXX](https://vocab.nerc.ac.uk/collection/P01/current/VOLXXXXX/)	changed from: Sample volume	to: Volume of sample
[VOLFFMXX](https://vocab.nerc.ac.uk/collection/P01/current/VOLFFMXX/)	changed from: Sample volume (filtration) by flow meter	to: Volume of sample (filtered) from the water body by flow meter
[VOLFMCXX](https://vocab.nerc.ac.uk/collection/P01/current/VOLFMCXX/)	changed from: Sample volume (filtration) by measuring cylinder	to: Volume of sample (filtered) from the water body by measuring cylinder
[VOLSEDSM](https://vocab.nerc.ac.uk/collection/P01/current/VOLSEDSM/)	changed from: Volume sampled of sediment	to: Volume of sample from the sediment
[VOLWBSMP](https://vocab.nerc.ac.uk/collection/P01/current/VOLWBSMP/)	changed from: Volume sampled of the water body	to: Volume of sample from the water body
[M91BA36A](https://vocab.nerc.ac.uk/collection/P01/current/M91BA36A/)	changed from: Sample volume (Plankton Visual Analyser)	to: Volume of sample from the water body by Plankton Visual Analyser
[VOLSPOPC](https://vocab.nerc.ac.uk/collection/P01/current/VOLSPOPC/)	changed from: Sample volume (optical plankton recorder count)	to: Volume of sample from the water body by optical plankton counter
