### ISSUE TITLE
NTR: Request for S18 glider phase (BODCNVS-1083)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S18#3]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>glider phase <p><b>Definition</b><p> The distinct operating stage recognised following the deployment of a glider platform into water and prior to recovery. The term is used for glider platforms capable of sub-surface travel.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://doi.org/10.13155/34980<p>

**Comment by gwemon** [comment]
Relates to: https://github.com/nvs-vocabs/P01/issues/83

**Comment by danibodc** [comment]
The above term has now been created:

**Code:** S1800094	
**Preferred label:** glider phase	
**Description:** The distinct operating stage recognised following the deployment of a glider platform into water and prior to recovery. The term is used for glider platforms capable of sub-surface travel.

It will be live on the NVS from 0730 UTC tomorrow morning.

**Comment by danibodc** [comment]
This code is now live:
https://vocab.nerc.ac.uk/collection/S18/current/S1800094/
