### ISSUE TITLE
NTR: Request for S18 surface microlayer (BODCNVS-1079)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S18#4]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>surface microlayer <p><b>Definition</b><p> The uppermost layer of water bodies representing a thin boundary layer (or skin) between the hydrosphere (mainly the ocean) and the atmosphere. It is nominally defined as the top 1000 micrometres (or 1 millimetre) of the ocean surface. <p><H2> Optional </H2><p><b>Sources/references</b><p> multiple<p>

**Comment by gwemon** [comment]
Linked to https://github.com/nvs-vocabs/P01/issues/76

**Comment by bodcmahe** [comment]
Term published:
http://vocab.nerc.ac.uk/collection/S18/current/S1800096/

Have subsequently modified the S18 description to refer to 'water's surface', not 'ocean surface' at the end (and mirrored in S29). Update will appear online overnight.

**Comment by gwemon** [comment]
Thank you @bodcmahe. I also added the following to the description: "Some observation methods like e.g. radiometry, distinguish between the skin (upper 10 - 20 micrometres below the air-sea interface) and the subskin (a sub-layer that is at a depth of approximately 1 - 1.5 millimetres below the air-sea interface)."
