### ISSUE TITLE
NTR: Request for S18 radial vector (BODCNVS-368)

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S18#5]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>radial vector <p><b>Definition</b><p> A line connecting a central reference point to a target object or particle of matter. <p><H2> Optional </H2><p><b>Sources/references</b><p> https://github.com/nvs-vocabs/P01/issues/49<p>

**Comment by bodcmahe** [comment]
Modified definition (see discussion in https://github.com/nvs-vocabs/P01/issues/49):

The linear polar co-ordinate of a vector measurement

**Comment by bodcmahe** [comment]
Term published:

http://vocab.nerc.ac.uk/collection/S18/current/S1800095/
