### ISSUE TITLE
NTR: Request for S18 pixel

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S18#6]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>pixel <p><b>Definition</b><p> The smallest addressable element of a digital image.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://github.com/nvs-vocabs/P01/issues/91<p>

**Comment by gwemon** [comment]
Term queued for publication on the NVS at 0630UTC tomorrow AM.

**Comment by gwemon** [comment]
Term live on the NVS: http://vocab.nerc.ac.uk/collection/S18/current/S1800097/
