### ISSUE TITLE
NTR: Request for S18 carbon/nitrogen

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S18#7]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>carbon/nitrogen <p><b>Definition</b><p> Ratio of elemental carbon to elemental nitrogen. .<p><H2> Optional </H2><p><b>Sources/references</b><p> https://github.com/nvs-vocabs/P01/issues/72
https://en.wikipedia.org/wiki/Carbon-to-nitrogen_ratio<p>

**Comment by gwemon** [comment]
S1800098	carbon/nitrogen created and queued for publication on the NVS

**Comment by gwemon** [comment]
Live on the NVS: http://vocab.nerc.ac.uk/collection/S18/current/S1800098/
