### ISSUE TITLE
NTR: Request for S18 Secchi disk

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S18#8]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>Secchi disk <p><b>Definition</b><p> A disk, divided into black and white quarters, used to gauge water clarity by measuring the depth at which it is no longer visible from the surface.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://www.sciencedirect.com/topics/agricultural-and-biological-sciences/secchi-disk<p>

**Comment by danibodc** [comment]
This term is now live on the NVS:
https://vocab.nerc.ac.uk/collection/S18/current/S1800099/
