### ISSUE TITLE
NTR: Request for S18 single particle

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S18#9]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>single particle <p><b>Definition</b><p> The property relates to a single particle.<p><H2> Optional </H2><p><b>Sources/references</b><p> https://github.com/nvs-vocabs/P01/issues/127<p>

**Comment by gwemon** [comment]
The new term has been added to S18 and queued for publication on the NVS. The corresponding S29 term has been created.

**Comment by gwemon** [comment]
Live in the NVS: http://vocab.nerc.ac.uk/collection/S18/current/S1800100/
